
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 23 02:25:57 CST 2021
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 12;
  public static final int DOSPUNTOS = 26;
  public static final int WHEN = 30;
  public static final int FUNCTION = 36;
  public static final int PUT = 20;
  public static final int TIPOVARIABLE = 7;
  public static final int ELSIF = 17;
  public static final int CONDICIONALES = 18;
  public static final int FOR = 24;
  public static final int SEMICOLON = 4;
  public static final int OPSUMA = 33;
  public static final int IS = 5;
  public static final int IN = 25;
  public static final int GET = 23;
  public static final int BEGIN = 8;
  public static final int OPREL = 13;
  public static final int LOOP = 27;
  public static final int EXIT = 29;
  public static final int IF = 11;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int PARIZQ = 21;
  public static final int RETURN = 35;
  public static final int TRUE = 14;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int ASIGNACION = 31;
  public static final int DECLARACION = 6;
  public static final int ELSE = 19;
  public static final int WHILE = 28;
  public static final int THEN = 16;
  public static final int NUMINT = 37;
  public static final int OPMULTIPLICACION = 34;
  public static final int END = 10;
  public static final int NUMFLOAT = 38;
  public static final int STRING = 9;
  public static final int FALSE = 15;
  public static final int PARDER = 22;
  public static final int PROCEDURE = 2;
}

