
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 15 00:22:02 CST 2021
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECLARACION = 6;
  public static final int PROCEDURE = 2;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int ID = 3;
  public static final int error = 1;
  public static final int TIPOVARIABLE = 7;
  public static final int SEMICOLON = 4;
  public static final int END = 10;
  public static final int BEGIN = 8;
  public static final int IS = 5;
}

